//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.Sjalvdeklaration.Shared.Resources.Classes.Log {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Difi.Sjalvdeklaration.Shared.Resources.Classes.Log.LogItem", typeof(LogItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funksjonsanropsparameter 1.
        /// </summary>
        internal static string Call_parameter_1 {
            get {
                return ResourceManager.GetString("Call parameter 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funksjonsanropsparameter 2.
        /// </summary>
        internal static string Call_parameter_2 {
            get {
                return ResourceManager.GetString("Call parameter 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprettet dato.
        /// </summary>
        internal static string Created_date {
            get {
                return ResourceManager.GetString("Created date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funksjon.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultatfeil.
        /// </summary>
        internal static string Result_error {
            get {
                return ResourceManager.GetString("Result error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultat id.
        /// </summary>
        internal static string Result_id {
            get {
                return ResourceManager.GetString("Result id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultat lyktes.
        /// </summary>
        internal static string Result_succeeded {
            get {
                return ResourceManager.GetString("Result succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultattekst.
        /// </summary>
        internal static string Result_text {
            get {
                return ResourceManager.GetString("Result text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seksjon.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruker.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
