//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.Sjalvdeklaration.Shared.Resources.Classes.Company {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanyItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Difi.Sjalvdeklaration.Shared.Resources.Classes.Company.CompanyItem", typeof(CompanyItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sted.
        /// </summary>
        internal static string BusinessAddressCity {
            get {
                return ResourceManager.GetString("BusinessAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beliggenhetsadresse sted er påkrevd.
        /// </summary>
        internal static string BusinessAddressCity___required_field {
            get {
                return ResourceManager.GetString("BusinessAddressCity - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatenavn og nummer.
        /// </summary>
        internal static string BusinessAddressStreet {
            get {
                return ResourceManager.GetString("BusinessAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beliggenhetsadresse gatenavn og nummer er påkrevd.
        /// </summary>
        internal static string BusinessAddressStreet___required_field {
            get {
                return ResourceManager.GetString("BusinessAddressStreet - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer.
        /// </summary>
        internal static string BusinessAddressZip {
            get {
                return ResourceManager.GetString("BusinessAddressZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beliggenhetsadresse postnummer er påkrevd.
        /// </summary>
        internal static string BusinessAddressZip___required_field {
            get {
                return ResourceManager.GetString("BusinessAddressZip - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinkode.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinkode er påkrevd.
        /// </summary>
        internal static string Code___required_field {
            get {
                return ResourceManager.GetString("Code - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virksomhet ID (tilsynets datamodell).
        /// </summary>
        internal static string CorporateIdentityNumber {
            get {
                return ResourceManager.GetString("CorporateIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virksomhet ID er påkrevd.
        /// </summary>
        internal static string CorporateIdentityNumber___required_field {
            get {
                return ResourceManager.GetString("CorporateIdentityNumber - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CustomAddressCity.
        /// </summary>
        internal static string CustomAddressCity {
            get {
                return ResourceManager.GetString("CustomAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CustomAddressCity - er påkrevd.
        /// </summary>
        internal static string CustomAddressCity___required_field {
            get {
                return ResourceManager.GetString("CustomAddressCity - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CustomAddressStreet.
        /// </summary>
        internal static string CustomAddressStreet {
            get {
                return ResourceManager.GetString("CustomAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CustomAddressStreet - er påkrevd.
        /// </summary>
        internal static string CustomAddressStreet___required_field {
            get {
                return ResourceManager.GetString("CustomAddressStreet - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CustomAddressZip.
        /// </summary>
        internal static string CustomAddressZip {
            get {
                return ResourceManager.GetString("CustomAddressZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CustomAddressZip - er påkrevd.
        /// </summary>
        internal static string CustomAddressZip___required_field {
            get {
                return ResourceManager.GetString("CustomAddressZip - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CustomName.
        /// </summary>
        internal static string CustomName {
            get {
                return ResourceManager.GetString("CustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CustomName - er påkrevd.
        /// </summary>
        internal static string CustomName___required_field {
            get {
                return ResourceManager.GetString("CustomName - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næringsgruppe aggregert.
        /// </summary>
        internal static string IndustryGroupAggregated {
            get {
                return ResourceManager.GetString("IndustryGroupAggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næringsgruppe aggregert er påkrevd.
        /// </summary>
        internal static string IndustryGroupAggregated___required_field {
            get {
                return ResourceManager.GetString("IndustryGroupAggregated - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næringsgruppe kode.
        /// </summary>
        internal static string IndustryGroupCode {
            get {
                return ResourceManager.GetString("IndustryGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næringsgruppe kode er påkrevd.
        /// </summary>
        internal static string IndustryGroupCode___required_field {
            get {
                return ResourceManager.GetString("IndustryGroupCode - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næringsgruppe beskrivelse.
        /// </summary>
        internal static string IndustryGroupDescription {
            get {
                return ResourceManager.GetString("IndustryGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næringsgruppe beskrivelse er påkrevd.
        /// </summary>
        internal static string IndustryGroupDescription___required_field {
            get {
                return ResourceManager.GetString("IndustryGroupDescription - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institusjonell sektorkode kode.
        /// </summary>
        internal static string InstitutionalSectorCode {
            get {
                return ResourceManager.GetString("InstitutionalSectorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institusjonell sektorkode kode er påkrevd.
        /// </summary>
        internal static string InstitutionalSectorCode___required_field {
            get {
                return ResourceManager.GetString("InstitutionalSectorCode - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institusjonell sektorkode beskrivelse.
        /// </summary>
        internal static string InstitutionalSectorDescription {
            get {
                return ResourceManager.GetString("InstitutionalSectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institusjonell sektorkode beskrivelse er påkrevd.
        /// </summary>
        internal static string InstitutionalSectorDescription___required_field {
            get {
                return ResourceManager.GetString("InstitutionalSectorDescription - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sted.
        /// </summary>
        internal static string LocationAddressCity {
            get {
                return ResourceManager.GetString("LocationAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forretningsadresse sted er påkrevd.
        /// </summary>
        internal static string LocationAddressCity___required_field {
            get {
                return ResourceManager.GetString("LocationAddressCity - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatenavn og nummer.
        /// </summary>
        internal static string LocationAddressStreet {
            get {
                return ResourceManager.GetString("LocationAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forretningsadresse gatenavn og nummer er åkrevd.
        /// </summary>
        internal static string LocationAddressStreet___required_field {
            get {
                return ResourceManager.GetString("LocationAddressStreet - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer.
        /// </summary>
        internal static string LocationAddressZip {
            get {
                return ResourceManager.GetString("LocationAddressZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forretningsadresse postnummer er påkrevd.
        /// </summary>
        internal static string LocationAddressZip___required_field {
            get {
                return ResourceManager.GetString("LocationAddressZip - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sted.
        /// </summary>
        internal static string MailingAddressCity {
            get {
                return ResourceManager.GetString("MailingAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sted er påkrevd.
        /// </summary>
        internal static string MailingAddressCity___required_field {
            get {
                return ResourceManager.GetString("MailingAddressCity - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatenavn og nummer.
        /// </summary>
        internal static string MailingAddressStreet {
            get {
                return ResourceManager.GetString("MailingAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatenavn og nummer er påkrevd.
        /// </summary>
        internal static string MailingAddressStreet___required_field {
            get {
                return ResourceManager.GetString("MailingAddressStreet - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer.
        /// </summary>
        internal static string MailingAddressZip {
            get {
                return ResourceManager.GetString("MailingAddressZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer er påkrevd.
        /// </summary>
        internal static string MailingAddressZip___required_field {
            get {
                return ResourceManager.GetString("MailingAddressZip - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virksomhetens navn i Brreg.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virksomhetens navn i Brreg er påkrevd.
        /// </summary>
        internal static string Name___required_field {
            get {
                return ResourceManager.GetString("Name - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisationsnummer.
        /// </summary>
        internal static string OwnerCorporateIdentityNumber {
            get {
                return ResourceManager.GetString("OwnerCorporateIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisationsnummer er påkrevd.
        /// </summary>
        internal static string OwnerCorporateIdentityNumber___required_field {
            get {
                return ResourceManager.GetString("OwnerCorporateIdentityNumber - required field", resourceCulture);
            }
        }
    }
}
