//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.Sjalvdeklaration.Shared.Resources.Classes.Company {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanyItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Difi.Sjalvdeklaration.Shared.Resources.Classes.Company.CompanyItem", typeof(CompanyItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregert.
        /// </summary>
        internal static string Aggregated {
            get {
                return ResourceManager.GetString("Aggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virksomhet ID (tilsynets datamodell).
        /// </summary>
        internal static string Business_ID__Supervisory_Data_Model_ {
            get {
                return ResourceManager.GetString("Business ID (Supervisory Data Model)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endret navn på virksomheten.
        /// </summary>
        internal static string Changed_business_name {
            get {
                return ResourceManager.GetString("Changed business name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sted.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kode.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virksomhet.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virksomhet er påkrevd.
        /// </summary>
        internal static string Name_is_required {
            get {
                return ResourceManager.GetString("Name is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnummer.
        /// </summary>
        internal static string Organization_number {
            get {
                return ResourceManager.GetString("Organization number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnummer på hovedorgansasjonen.
        /// </summary>
        internal static string Organization_number_of_the_owner_organization {
            get {
                return ResourceManager.GetString("Organization number of the owner organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinkode.
        /// </summary>
        internal static string Pin_code {
            get {
                return ResourceManager.GetString("Pin code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatenavn og nummer.
        /// </summary>
        internal static string Street_name_and_number {
            get {
                return ResourceManager.GetString("Street name and number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer.
        /// </summary>
        internal static string ZIP_code {
            get {
                return ResourceManager.GetString("ZIP code", resourceCulture);
            }
        }
    }
}
