//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.Sjalvdeklaration.Shared.Resources.Classes.Company {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactPersonItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactPersonItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Difi.Sjalvdeklaration.Shared.Resources.Classes.Company.ContactPersonItem", typeof(ContactPersonItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epostadresse til kontaktperson.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epostadresse til kontaktperson er påkrevd.
        /// </summary>
        internal static string Email___required_field {
            get {
                return ResourceManager.GetString("Email - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på kontaktperson.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på kontaktperson er påkrevd.
        /// </summary>
        internal static string Name___required_field {
            get {
                return ResourceManager.GetString("Name - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer til kontaktperson.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer til kontaktperson er påkrevd.
        /// </summary>
        internal static string Phone___required_field {
            get {
                return ResourceManager.GetString("Phone - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer Landskode til kontaktperson.
        /// </summary>
        internal static string PhoneCountryCode {
            get {
                return ResourceManager.GetString("PhoneCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer Landskode til kontaktperson er påkrevd.
        /// </summary>
        internal static string PhoneCountryCode___required_field {
            get {
                return ResourceManager.GetString("PhoneCountryCode - required field", resourceCulture);
            }
        }
    }
}
