//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.Sjalvdeklaration.Shared.Resources.Classes.Declaration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeclarationTestItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeclarationTestItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Difi.Sjalvdeklaration.Shared.Resources.Classes.Declaration.DeclarationTestItem", typeof(DeclarationTestItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg fra listen hvilken produsent og modell betalingsterminal du skal kontrollere.
        /// </summary>
        internal static string Choose_from_the_list_which_manufacturer_and_model_payment_terminal_you_should_check {
            get {
                return ResourceManager.GetString("Choose from the list which manufacturer and model payment terminal you should che" +
                        "ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskriv hvilken betalingsterminal du velger å kontrollere.
        /// </summary>
        internal static string Describe_which_payment_terminal_you_choose_to_control {
            get {
                return ResourceManager.GetString("Describe which payment terminal you choose to control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvik eller merknad.
        /// </summary>
        internal static string Deviation_or_Notice {
            get {
                return ResourceManager.GetString("Deviation or Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difi trenger å vite hvilken betalingsterminal du kontrollerer og sender inn opplysninger om..
        /// </summary>
        internal static string Difi_needs_to_know_which_payment_terminal_you_check_and_submit_information_about_ {
            get {
                return ResourceManager.GetString("Difi needs to know which payment terminal you check and submit information about." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har en automat.
        /// </summary>
        internal static string Has_a_machine {
            get {
                return ResourceManager.GetString("Has a machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her kan du for eksempel skrive hvor betalingsterminalen er plassert. &lt;br /&gt;Eksempler er kasse 1, nærmest inngangen/utgangen, den til venstre for Inngangen/utgangen..
        /// </summary>
        internal static string Here_you_can__for_example__type_where_the_payment_terminal_is_located___br____Examples_are_cash_register_1__closest_to_the_the_entrance___exit__to_the_left_of_the_the_entrance___exit_ {
            get {
                return ResourceManager.GetString("Here you can, for example, type where the payment terminal is located. <br /> Exa" +
                        "mples are cash register 1, closest to the the entrance / exit, to the left of th" +
                        "e the entrance / exit.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produsent og navn på automat.
        /// </summary>
        internal static string Manufacturer_and_name_of_automat {
            get {
                return ResourceManager.GetString("Manufacturer and name of automat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formål med test.
        /// </summary>
        internal static string Purpose_of_test {
            get {
                return ResourceManager.GetString("Purpose of test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta et nærbilde av betalingsterminalen du skal registrere opplysninger om.
        /// </summary>
        internal static string Take_a_close_up_of_the_payment_terminal_you_are_going_to_register_information_about {
            get {
                return ResourceManager.GetString("Take a close-up of the payment terminal you are going to register information abo" +
                        "ut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta et oversiktsbilde av betalingsterminalen du skal registrere opplysninger om. Bildet skal vise hvor betalingsterminalen er plassert.
        /// </summary>
        internal static string Take_a_survey_of_the_payment_terminal_to_register_information_about__The_image_will_show_where_the_payment_terminal_is_located {
            get {
                return ResourceManager.GetString("Take a survey of the payment terminal to register information about. The image wi" +
                        "ll show where the payment terminal is located", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildet skal vise hvor betalingsterminalen er plassert. Bildet skal vise hele betalingsterminalen og området foran terminalen..
        /// </summary>
        internal static string The_image_should_show_where_the_payment_terminal_is_located__The_image_should_show_the_entire_payment_terminal_and_the_area_in_front_of_the_terminal_ {
            get {
                return ResourceManager.GetString("The image should show where the payment terminal is located. The image should sho" +
                        "w the entire payment terminal and the area in front of the terminal.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type automat.
        /// </summary>
        internal static string Type_of_machine {
            get {
                return ResourceManager.GetString("Type of machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ikt-løsning.
        /// </summary>
        internal static string Type_of_test {
            get {
                return ResourceManager.GetString("Type of test", resourceCulture);
            }
        }
    }
}
