//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.Sjalvdeklaration.Shared.Resources.Classes.Declaration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeclarationTestItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeclarationTestItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Difi.Sjalvdeklaration.Shared.Resources.Classes.Declaration.DeclarationTestItem", typeof(DeclarationTestItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4CaseNumber.
        /// </summary>
        internal static string CaseNumber {
            get {
                return ResourceManager.GetString("CaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4CaseNumber - er påkrevd.
        /// </summary>
        internal static string CaseNumber___required_field {
            get {
                return ResourceManager.GetString("CaseNumber - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DeclarationItem.
        /// </summary>
        internal static string DeclarationItem {
            get {
                return ResourceManager.GetString("DeclarationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DeclarationItem - er påkrevd.
        /// </summary>
        internal static string DeclarationItem___required_field {
            get {
                return ResourceManager.GetString("DeclarationItem - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DescriptionInText.
        /// </summary>
        internal static string DescriptionInText {
            get {
                return ResourceManager.GetString("DescriptionInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DescriptionInText - er påkrevd.
        /// </summary>
        internal static string DescriptionInText___required_field {
            get {
                return ResourceManager.GetString("DescriptionInText - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4FinishedStatus.
        /// </summary>
        internal static string FinishedStatus {
            get {
                return ResourceManager.GetString("FinishedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4FinishedStatus - er påkrevd.
        /// </summary>
        internal static string FinishedStatus___required_field {
            get {
                return ResourceManager.GetString("FinishedStatus - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Image1.
        /// </summary>
        internal static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Image1 - er påkrevd.
        /// </summary>
        internal static string Image1___required_field {
            get {
                return ResourceManager.GetString("Image1 - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Image2.
        /// </summary>
        internal static string Image2 {
            get {
                return ResourceManager.GetString("Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Image2 - er påkrevd.
        /// </summary>
        internal static string Image2___required_field {
            get {
                return ResourceManager.GetString("Image2 - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4OutcomeDataList.
        /// </summary>
        internal static string OutcomeDataList {
            get {
                return ResourceManager.GetString("OutcomeDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4OutcomeDataList - er påkrevd.
        /// </summary>
        internal static string OutcomeDataList___required_field {
            get {
                return ResourceManager.GetString("OutcomeDataList - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4SupplierAndVersion.
        /// </summary>
        internal static string SupplierAndVersion {
            get {
                return ResourceManager.GetString("SupplierAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4SupplierAndVersion - er påkrevd.
        /// </summary>
        internal static string SupplierAndVersion___required_field {
            get {
                return ResourceManager.GetString("SupplierAndVersion - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4SupplierAndVersionOther.
        /// </summary>
        internal static string SupplierAndVersionOther {
            get {
                return ResourceManager.GetString("SupplierAndVersionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4SupplierAndVersionOther - er påkrevd.
        /// </summary>
        internal static string SupplierAndVersionOther___required_field {
            get {
                return ResourceManager.GetString("SupplierAndVersionOther - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4TypeOfMachine.
        /// </summary>
        internal static string TypeOfMachine {
            get {
                return ResourceManager.GetString("TypeOfMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4TypeOfMachine - er påkrevd.
        /// </summary>
        internal static string TypeOfMachine___required_field {
            get {
                return ResourceManager.GetString("TypeOfMachine - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4TypeOfTest.
        /// </summary>
        internal static string TypeOfTest {
            get {
                return ResourceManager.GetString("TypeOfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4TypeOfTest - er påkrevd.
        /// </summary>
        internal static string TypeOfTest___required_field {
            get {
                return ResourceManager.GetString("TypeOfTest - required field", resourceCulture);
            }
        }
    }
}
