//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.Sjalvdeklaration.Shared.Resources.Classes.Declaration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeclarationItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeclarationItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Difi.Sjalvdeklaration.Shared.Resources.Classes.Declaration.DeclarationItem", typeof(DeclarationItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Company - er påkrevd.
        /// </summary>
        internal static string Company___required_field {
            get {
                return ResourceManager.GetString("Company - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3CompanyItemId.
        /// </summary>
        internal static string CompanyItemId {
            get {
                return ResourceManager.GetString("CompanyItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3CompanyItemId - er påkrevd.
        /// </summary>
        internal static string CompanyItemId___required_field {
            get {
                return ResourceManager.GetString("CompanyItemId - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3CreatedDate.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3CreatedDate - er påkrevd.
        /// </summary>
        internal static string CreatedDate___required_field {
            get {
                return ResourceManager.GetString("CreatedDate - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DeadlineDate.
        /// </summary>
        internal static string DeadlineDate {
            get {
                return ResourceManager.GetString("DeadlineDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DeadlineDate - er påkrevd.
        /// </summary>
        internal static string DeadlineDate___required_field {
            get {
                return ResourceManager.GetString("DeadlineDate - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DeclarationTestItem.
        /// </summary>
        internal static string DeclarationTestItem {
            get {
                return ResourceManager.GetString("DeclarationTestItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DeclarationTestItem - er påkrevd.
        /// </summary>
        internal static string DeclarationTestItem___required_field {
            get {
                return ResourceManager.GetString("DeclarationTestItem - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3IndicatorList.
        /// </summary>
        internal static string IndicatorList {
            get {
                return ResourceManager.GetString("IndicatorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3IndicatorList - er påkrevd.
        /// </summary>
        internal static string IndicatorList___required_field {
            get {
                return ResourceManager.GetString("IndicatorList - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Name - er påkrevd.
        /// </summary>
        internal static string Name___required_field {
            get {
                return ResourceManager.GetString("Name - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3SentInDate.
        /// </summary>
        internal static string SentInDate {
            get {
                return ResourceManager.GetString("SentInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3SentInDate - er påkrevd.
        /// </summary>
        internal static string SentInDate___required_field {
            get {
                return ResourceManager.GetString("SentInDate - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Status - er påkrevd.
        /// </summary>
        internal static string Status___required_field {
            get {
                return ResourceManager.GetString("Status - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3User - er påkrevd.
        /// </summary>
        internal static string User___required_field {
            get {
                return ResourceManager.GetString("User - required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3UserItemId.
        /// </summary>
        internal static string UserItemId {
            get {
                return ResourceManager.GetString("UserItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3UserItemId - er påkrevd.
        /// </summary>
        internal static string UserItemId___required_field {
            get {
                return ResourceManager.GetString("UserItemId - required field", resourceCulture);
            }
        }
    }
}
